FROM ubuntu:24.04
RUN apt-get update && apt-get install -dy --no-install-recommends \
  bbe \
  bison \
  build-essential \
  ca-certificates \
  clang-14 \
  cmake \
  git \
  liblz4-dev \
  libncurses-dev \
  libssl-dev \
  ninja-build \
  zlib1g-dev
